version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    # environment:
    #   - ELASTICSEARCH_HOST=elasticsearch:9200
    networks:
      - final_demo
    restart: always

  # elastic 


networks:
  final_demo:
